In [79]:
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.static import players
from nba_api.stats.endpoints import drafthistory
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_players()
# Anthony Davis
career = playercareerstats.PlayerCareerStats(per_mode36 = 'PerGame',player_id='203076')
#career = playercareerstats._init_(career_totals_college_season)
career.season_totals_regular_season.get_data_frame()
career.get_dict()
#career.load_response()

{'resource': 'playercareerstats',
 'parameters': {'PerMode': 'PerGame', 'PlayerID': 203076, 'LeagueID': None},
 'resultSets': [{'name': 'SeasonTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '2012-13',
     '00',
     1610612740,
     'NOH',
     20.0,
     64,
     60,
     28.8,
     5.5,
     10.6,
     0.516,
     0.0,
     0.1,
     0.0,
     2.6,
     3.5,
     0.751,
     2.6,
     5.6,
     8.2,
     1.0,
     1.2,
     1.8,
     1.4,
     2.5,
     13.5],
    [203076,
     '2013-14',
     '00',
     1610612740,
     'NOP',
     21.0,
     67,
     66,
     35.2,
     7.8,
     15.0,
     0.519,
     0.0,
     0.1,
     0.222,
     5.2,
     6.6,
     0.791,
     3.1,
     7.0,
     10.0,
     1.6,
     1.3,
     2.8,
     1.6,
     3.0,
     20.8],
    [203076,
     '2014-15',
     '00',
     1610612740,
     'NOP',
     22.0,
     68,
     68,
     36.1,
     9.4,
     17.6,
     0.535,
     0.0,
     0.2,
     0.083,
     5.5,
     6.8,
     0.805,
     2.5,
     7.7,
     10.2,
     2.2,
     1.5,
     2.9,
     1.4,
     2.1,
     24.4],
    [203076,
     '2015-16',
     '00',
     1610612740,
     'NOP',
     23.0,
     61,
     61,
     35.5,
     9.2,
     18.6,
     0.493,
     0.6,
     1.8,
     0.324,
     5.3,
     7.0,
     0.758,
     2.1,
     8.1,
     10.3,
     1.9,
     1.3,
     2.0,
     2.0,
     2.4,
     24.3],
    [203076,
     '2016-17',
     '00',
     1610612740,
     'NOP',
     24.0,
     75,
     75,
     36.1,
     10.3,
     20.3,
     0.505,
     0.5,
     1.8,
     0.299,
     6.9,
     8.6,
     0.802,
     2.3,
     9.5,
     11.8,
     2.1,
     1.3,
     2.2,
     2.4,
     2.2,
     28.0],
    [203076,
     '2017-18',
     '00',
     1610612740,
     'NOP',
     25.0,
     75,
     75,
     36.4,
     10.4,
     19.5,
     0.534,
     0.7,
     2.2,
     0.34,
     6.6,
     8.0,
     0.828,
     2.5,
     8.6,
     11.1,
     2.3,
     1.5,
     2.6,
     2.2,
     2.1,
     28.1],
    [203076,
     '2018-19',
     '00',
     1610612740,
     'NOP',
     26.0,
     56,
     56,
     33.0,
     9.5,
     18.3,
     0.517,
     0.9,
     2.6,
     0.331,
     6.1,
     7.7,
     0.794,
     3.1,
     8.9,
     12.0,
     3.9,
     1.6,
     2.4,
     2.0,
     2.4,
     25.9],
    [203076,
     '2019-20',
     '00',
     1610612747,
     'LAL',
     27.0,
     62,
     62,
     34.4,
     8.9,
     17.7,
     0.503,
     1.2,
     3.5,
     0.33,
     7.2,
     8.5,
     0.846,
     2.3,
     7.0,
     9.3,
     3.2,
     1.5,
     2.3,
     2.5,
     2.5,
     26.1],
    [203076,
     '2020-21',
     '00',
     1610612747,
     'LAL',
     28.0,
     36,
     36,
     32.3,
     8.4,
     17.0,
     0.491,
     0.7,
     2.8,
     0.26,
     4.4,
     5.9,
     0.738,
     1.7,
     6.2,
     7.9,
     3.1,
     1.3,
     1.6,
     2.1,
     1.7,
     21.8],
    [203076,
     '2021-22',
     '00',
     1610612747,
     'LAL',
     29.0,
     40,
     40,
     35.1,
     9.3,
     17.4,
     0.532,
     0.3,
     1.8,
     0.186,
     4.4,
     6.1,
     0.713,
     2.7,
     7.2,
     9.9,
     3.1,
     1.2,
     2.3,
     2.1,
     2.4,
     23.2]]},
  {'name': 'CareerTotalsRegularSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '00',
     0,
     604,
     599,
     34.4,
     8.9,
     17.3,
     0.515,
     0.5,
     1.6,
     0.303,
     5.5,
     7.0,
     0.794,
     2.5,
     7.7,
     10.2,
     2.3,
     1.4,
     2.3,
     2.0,
     2.3,
     23.8]]},
  {'name': 'SeasonTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '2014-15',
     '00',
     1610612740,
     'NOP',
     22.0,
     4,
     4,
     42.9,
     11.8,
     21.8,
     0.54,
     0.0,
     0.5,
     0.0,
     8.0,
     9.0,
     0.889,
     2.3,
     8.8,
     11.0,
     2.0,
     1.3,
     3.0,
     3.3,
     3.0,
     31.5],
    [203076,
     '2017-18',
     '00',
     1610612740,
     'NOP',
     25.0,
     9,
     9,
     39.8,
     11.8,
     22.7,
     0.52,
     0.7,
     2.4,
     0.273,
     5.9,
     7.1,
     0.828,
     2.7,
     10.8,
     13.4,
     1.7,
     2.0,
     2.3,
     2.6,
     3.3,
     30.1],
    [203076,
     '2019-20',
     '00',
     1610612747,
     'LAL',
     27.0,
     21,
     21,
     36.6,
     9.8,
     17.1,
     0.571,
     1.1,
     2.9,
     0.383,
     7.1,
     8.5,
     0.832,
     2.6,
     7.1,
     9.7,
     3.5,
     1.2,
     1.4,
     2.5,
     2.7,
     27.7],
    [203076,
     '2020-21',
     '00',
     1610612747,
     'LAL',
     28.0,
     5,
     5,
     28.8,
     5.0,
     12.4,
     0.403,
     0.4,
     2.2,
     0.182,
     7.0,
     8.4,
     0.833,
     1.4,
     5.2,
     6.6,
     2.6,
     0.6,
     1.6,
     1.2,
     1.8,
     17.4]]},
  {'name': 'CareerTotalsPostSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '00',
     0,
     39,
     39,
     37.0,
     9.8,
     18.3,
     0.538,
     0.8,
     2.4,
     0.326,
     6.9,
     8.2,
     0.838,
     2.4,
     7.9,
     10.3,
     2.8,
     1.3,
     1.8,
     2.4,
     2.7,
     27.3]]},
  {'name': 'SeasonTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '2013-14',
     '00',
     1610616834,
     'WST',
     21.0,
     1,
     0,
     9.6,
     5.0,
     6.0,
     0.833,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     1.0,
     1.0,
     0.0,
     2.0,
     0.0,
     1.0,
     0.0,
     10.0],
    [203076,
     '2015-16',
     '00',
     1610616834,
     'WST',
     23.0,
     1,
     0,
     15.3,
     12.0,
     13.0,
     0.923,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     3.0,
     3.0,
     6.0,
     0.0,
     1.0,
     0.0,
     0.0,
     1.0,
     24.0],
    [203076,
     '2016-17',
     '00',
     1610616834,
     'WST',
     24.0,
     1,
     1,
     31.8,
     26.0,
     39.0,
     0.667,
     0.0,
     4.0,
     0.0,
     0.0,
     0.0,
     0.0,
     4.0,
     6.0,
     10.0,
     0.0,
     2.0,
     0.0,
     1.0,
     1.0,
     52.0],
    [203076,
     '2017-18',
     '00',
     1610616833,
     'LBN',
     25.0,
     1,
     1,
     16.7,
     6.0,
     9.0,
     0.667,
     0.0,
     1.0,
     0.0,
     0.0,
     0.0,
     0.0,
     1.0,
     1.0,
     2.0,
     1.0,
     0.0,
     0.0,
     1.0,
     2.0,
     12.0],
    [203076,
     '2018-19',
     '00',
     1610616834,
     'LBN',
     26.0,
     1,
     0,
     4.9,
     2.0,
     2.0,
     1.0,
     1.0,
     1.0,
     1.0,
     0.0,
     0.0,
     0.0,
     0.0,
     1.0,
     1.0,
     0.0,
     0.0,
     0.0,
     0.0,
     0.0,
     5.0],
    [203076,
     '2019-20',
     '00',
     1610616834,
     'LBN',
     27.0,
     1,
     1,
     20.4,
     9.0,
     16.0,
     0.563,
     1.0,
     6.0,
     0.167,
     1.0,
     2.0,
     0.5,
     2.0,
     7.0,
     9.0,
     1.0,
     3.0,
     3.0,
     1.0,
     3.0,
     20.0]]},
  {'name': 'CareerTotalsAllStarSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '00',
     0,
     6,
     3,
     16.4,
     10.0,
     14.2,
     0.706,
     0.3,
     2.0,
     0.167,
     0.2,
     0.3,
     0.5,
     1.7,
     3.2,
     4.8,
     0.3,
     1.3,
     0.5,
     0.7,
     1.2,
     20.5]]},
  {'name': 'SeasonTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'SCHOOL_NAME',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '2011-12',
     '00',
     2852,
     'Kentucky',
     19.0,
     40,
     40,
     32.0,
     5.3,
     8.4,
     0.623,
     0.1,
     0.5,
     0.15,
     3.6,
     5.1,
     0.709,
     3.0,
     7.4,
     10.4,
     1.3,
     1.4,
     4.7,
     1.0,
     2.0,
     14.2]]},
  {'name': 'CareerTotalsCollegeSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'ORGANIZATION_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': [[203076,
     '00',
     0,
     40,
     40,
     32.0,
     5.3,
     8.4,
     0.623,
     0.1,
     0.5,
     0.15,
     3.6,
     5.1,
     0.709,
     3.0,
     7.4,
     10.4,
     1.3,
     1.4,
     4.7,
     1.0,
     2.0,
     14.2]]},
  {'name': 'SeasonTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'CareerTotalsShowcaseSeason',
   'headers': ['PLAYER_ID',
    'LEAGUE_ID',
    'Team_ID',
    'GP',
    'GS',
    'MIN',
    'FGM',
    'FGA',
    'FG_PCT',
    'FG3M',
    'FG3A',
    'FG3_PCT',
    'FTM',
    'FTA',
    'FT_PCT',
    'OREB',
    'DREB',
    'REB',
    'AST',
    'STL',
    'BLK',
    'TOV',
    'PF',
    'PTS'],
   'rowSet': []},
  {'name': 'SeasonRankingsRegularSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_PG_MIN',
    'RANK_PG_FGM',
    'RANK_PG_FGA',
    'RANK_FG_PCT',
    'RANK_PG_FG3M',
    'RANK_PG_FG3A',
    'RANK_FG3_PCT',
    'RANK_PG_FTM',
    'RANK_PG_FTA',
    'RANK_FT_PCT',
    'RANK_PG_OREB',
    'RANK_PG_DREB',
    'RANK_PG_REB',
    'RANK_PG_AST',
    'RANK_PG_STL',
    'RANK_PG_BLK',
    'RANK_PG_TOV',
    'RANK_PG_PTS',
    'RANK_PG_EFF'],
   'rowSet': [[203076,
     '2012-13',
     '00',
     1610612740,
     'NOH',
     'NR',
     'NR',
     'NR',
     None,
     None,
     None,
     23,
     None,
     None,
     None,
     None,
     None,
     85,
     None,
     None,
     None,
     None,
     None,
     11,
     None,
     None,
     None],
    [203076,
     '2013-14',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     26,
     11,
     11,
     21,
     199,
     199,
     None,
     10,
     10,
     63,
     10,
     14,
     10,
     144,
     31,
     1,
     92,
     15,
     4],
    [203076,
     '2014-15',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     6,
     1,
     1,
     7,
     214,
     214,
     None,
     6,
     6,
     57,
     24,
     8,
     8,
     104,
     27,
     1,
     117,
     4,
     1],
    [203076,
     '2015-16',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     14,
     5,
     5,
     28,
     162,
     162,
     None,
     10,
     10,
     88,
     38,
     7,
     9,
     117,
     37,
     4,
     50,
     7,
     7],
    [203076,
     '2016-17',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     8,
     1,
     1,
     23,
     191,
     191,
     None,
     7,
     7,
     62,
     23,
     4,
     7,
     110,
     34,
     2,
     27,
     4,
     3],
    [203076,
     '2017-18',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     8,
     2,
     2,
     16,
     157,
     157,
     None,
     3,
     3,
     37,
     12,
     6,
     5,
     96,
     14,
     1,
     39,
     2,
     1],
    [203076,
     '2018-19',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     None,
     None,
     None,
     30,
     None,
     None,
     None,
     None,
     None,
     66,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None],
    [203076,
     '2019-20',
     '00',
     1610612747,
     'LAL',
     'NR',
     'NR',
     'NR',
     21,
     12,
     12,
     25,
     140,
     140,
     133,
     4,
     4,
     35,
     19,
     15,
     18,
     74,
     14,
     3,
     35,
     10,
     4],
    [203076,
     '2020-21',
     '00',
     1610612747,
     'LAL',
     'NR',
     'NR',
     'NR',
     None,
     None,
     None,
     46,
     None,
     None,
     None,
     None,
     None,
     84,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None],
    [203076,
     '2021-22',
     '00',
     1610612747,
     'LAL',
     'NR',
     'NR',
     'NR',
     None,
     None,
     None,
     15,
     None,
     None,
     None,
     None,
     None,
     99,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None]]},
  {'name': 'SeasonRankingsPostSeason',
   'headers': ['PLAYER_ID',
    'SEASON_ID',
    'LEAGUE_ID',
    'TEAM_ID',
    'TEAM_ABBREVIATION',
    'PLAYER_AGE',
    'GP',
    'GS',
    'RANK_PG_MIN',
    'RANK_PG_FGM',
    'RANK_PG_FGA',
    'RANK_FG_PCT',
    'RANK_PG_FG3M',
    'RANK_PG_FG3A',
    'RANK_FG3_PCT',
    'RANK_PG_FTM',
    'RANK_PG_FTA',
    'RANK_FT_PCT',
    'RANK_PG_OREB',
    'RANK_PG_DREB',
    'RANK_PG_REB',
    'RANK_PG_AST',
    'RANK_PG_STL',
    'RANK_PG_BLK',
    'RANK_PG_TOV',
    'RANK_PG_PTS',
    'RANK_PG_EFF'],
   'rowSet': [[203076,
     '2014-15',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     1,
     1,
     1,
     12,
     102,
     102,
     None,
     2,
     2,
     14,
     20,
     6,
     7,
     62,
     26,
     1,
     6,
     1,
     1],
    [203076,
     '2017-18',
     '00',
     1610612740,
     'NOP',
     'NR',
     'NR',
     'NR',
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None,
     None],
    [203076,
     '2019-20',
     '00',
     1610612747,
     'LAL',
     'NR',
     'NR',
     'NR',
     22,
     8,
     8,
     5,
     83,
     83,
     41,
     6,
     6,
     32,
     9,
     14,
     14,
     38,
     22,
     4,
     28,
     7,
     3],
    [203076,
     '2020-21',
     '00',
     1610612747,
     'LAL',
     'NR',
     'NR',
     'NR',
     64,
     45,
     45,
     60,
     111,
     111,
     None,
     6,
     6,
     32,
     34,
     29,
     28,
     43,
     74,
     3,
     52,
     30,
     30]]}]}

In [24]:
g = []
big_fundamental = [player for player in nba_players
                   if player['full_name'] == 'Tim Duncan'][0]
g = big_fundamental
print(g["id"])

1495

In [8]:
from nba_api.stats.endpoints import commonplayerinfo

player = commonplayerinfo.CommonPlayerInfo(player_id = 203076)
display(player.available_seasons.get_data_frame())
player.player_headline_stats.get_data_frame()

   SEASON_ID
0      12012
1      22012
2      12013
3      22013
4      32013
5      12014
6      22014
7      42014
8      12015
9      22015
10     32015
11     12016
12     22016
13     32016
14     12017
15     22017
16     32017
17     42017
18     12018
19     22018
20     32018
21     12019
22     22019
23     32019
24     42019
25     12020
26     22020
27     42020
28     52020
29     12021
30     22021

   PLAYER_ID    PLAYER_NAME TimeFrame   PTS  AST  REB    PIE
0     203076  Anthony Davis   2021-22  23.2  3.1  9.9  0.159

In [1]:
#lastDraft = drafthistory.DraftHistory(season_year_nullable = '2012', overall_pick_nullable = 1)
#t = lastDraft.get_dict()
#print(t)
#print(t["resultSets"])
#h = t["resultSets"][0]
#print(h["rowSet"][0][0])

def getDraftPickID(season = '2021', overall_pick = None, top_picks = None):
    from nba_api.stats.endpoints import drafthistory
    lastDraft = drafthistory.DraftHistory(season_year_nullable = season, 
                                          overall_pick_nullable = overall_pick, topx_nullable = top_picks)
    data = lastDraft.get_dict()
    results = data["resultSets"][0]
    player_data = results["rowSet"][0]
    return player_data[0]

print(getDraftPickID(season = '2012'))

def getPlayerStats(Id,league = 'nba'):
    from nba_api.stats.endpoints import playercareerstats
    career = playercareerstats.PlayerCareerStats(per_mode36 = 'PerGame',player_id=Id)
    if league == 'college':
        #career = playercareerstats._init_(career_totals_college_season)
        return career.season_totals_college_season.get_data_frame()
    else:
        return career.season_totals_regular_season.get_data_frame()
    
def getDraftCombineStats(league = '00', season = '2021'):
    from nba_api.stats.endpoints import draftcombinestats
    stats = draftcombinestats.DraftCombineStats(league_id = league, season_all_time = season)
    return stats.get_data_frames()[0]

def getPlayerGames1(Id, season = '2021', seasonType = 'Regular Season'):
    from nba_api.stats.endpoints import playergamelog
    career = playergamelog.PlayerGameLog(player_id = Id , season = season, 
                                           season_type_all_star = seasonType)
    return career.get_data_frames()[0]

def getPlayerGames2(Id, season = '2021', seasonType = 'Regular Season'):
    from nba_api.stats.endpoints import playernextngames
    career = playernextngames.PlayerNextNGames(number_of_games = 74, player_id = Id , season_all = season, 
                                           season_type_all_star = seasonType)
    return career.get_data_frames()[0]

def getTeamBoxscore(Id):
    from nba_api.stats.endpoints import boxscoretraditionalv2
    boxscore = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id = Id)
    return boxscore.team_stats.get_data_frame()
    
#AD = getDraftPickID(season = '2012', overall_pick = '1')
#getPlayerStats(AD, league = 'college')
#getDraftCombineStats()
#getPlayerGames('203076', '2014')
#getTeamBoxscore('0021401223')

203076

In [2]:
AD = getDraftPickID(season = '2012', overall_pick = '1')
getPlayerStats(AD, league = 'college')

,PLAYER_ID,SEASON_ID,LEAGUE_ID,ORGANIZATION_ID,SCHOOL_NAME,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2011-12,00,2852,Kentucky,19.0,40,40,32.0,5.3,...,0.709,3.0,7.4,10.4,1.3,1.4,4.7,1.0,2.0,14.2

In [8]:
AD = getDraftPickID(season = '2016', overall_pick = '11')
getPlayerStats(AD, league = 'nba')

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,1627734,2016-17,00,1610612760,OKC,21.0,81,66,20.1,2.4,...,0.657,0.6,3.0,3.6,1.0,0.5,0.4,1.0,2.5,5.9
1,1627734,2017-18,00,1610612754,IND,22.0,74,19,24.5,4.6,...,0.750,2.2,5.5,7.7,2.0,0.5,0.4,1.9,3.0,11.6
2,1627734,2018-19,00,1610612754,IND,23.0,74,5,24.8,5.6,...,0.715,2.5,6.8,9.3,2.9,0.6,0.4,2.2,3.2,14.1
3,1627734,2019-20,00,1610612754,IND,24.0,62,62,34.8,7.4,...,0.723,3.0,9.4,12.4,5.0,0.8,0.5,2.7,3.1,18.5
4,1627734,2020-21,00,1610612754,IND,25.0,62,62,36.0,7.8,...,0.732,2.4,9.5,12.0,6.7,1.2,0.5,3.4,3.3,20.3
5,1627734,2021-22,00,1610612754,IND,26.0,47,46,34.7,7.0,...,0.740,3.3,8.8,12.1,5.0,1.0,0.5,3.0,3.1,18.9
6,1627734,2021-22,00,1610612758,SAC,26.0,15,15,33.6,7.5,...,0.743,3.1,9.3,12.3,5.8,0.9,0.3,3.5,3.8,18.9
7,1627734,2021-22,00,0,TOT,26.0,62,61,34.4,7.1,...,0.741,3.2,8.9,12.1,5.2,1.0,0.4,3.1,3.3,18.9

In [113]:
getDraftCombineStats(season = '2012')

,SEASON,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,HEIGHT_W_SHOES,HEIGHT_W_SHOES_FT_IN,...,STANDING_REACH_FT_IN,BODY_FAT_PCT,HAND_LENGTH,HAND_WIDTH,STANDING_VERTICAL_LEAP,MAX_VERTICAL_LEAP,LANE_AGILITY_TIME,MODIFIED_LANE_AGILITY_TIME,THREE_QUARTER_SPRINT,BENCH_PRESS
0,2012,203112,Quincy,Acy,Quincy Acy,PF,78.50,6' 6.5'',79.75,6' 7.75'',...,8' 10.5'',7.1,9.50,11.00,32.0,37.0,10.48,None,3.28,13.0
1,2012,203084,Harrison,Barnes,Harrison Barnes,SF-SG,79.00,6' 7'',80.00,6' 8'',...,8' 5.5'',9.6,9.00,8.50,38.0,39.5,10.93,None,3.16,15.0
2,2012,203115,Will,Barton,Will Barton,SG-SF,77.00,6' 5'',78.00,6' 6'',...,8' 6.5'',4.1,9.00,9.50,30.0,34.0,12.50,None,3.60,0.0
3,2012,203078,Bradley,Beal,Bradley Beal,SG,75.25,6' 3.25'',76.75,6' 4.75'',...,8' 4'',6.0,8.50,9.00,33.0,39.0,10.95,None,3.28,8.0
4,2012,12458,J'Covan,Brown,J'Covan Brown,PG,73.00,6' 1'',74.25,6' 2.25'',...,8' 0'',12.5,7.75,8.25,26.0,29.5,11.68,None,3.47,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2012,203138,Hollis,Thompson,Hollis Thompson,SF,78.75,6' 6.75'',80.00,6' 8'',...,8' 6.5'',6.0,8.25,9.75,28.5,36.5,11.72,None,3.38,6.0
57,2012,203079,Dion,Waiters,Dion Waiters,SG,74.50,6' 2.5'',76.00,6' 4'',...,8' 2'',8.5,8.50,9.50,NaN,NaN,NaN,None,NaN,NaN
58,2012,203091,Royce,White,Royce White,PF,79.00,6' 7'',80.00,6' 8'',...,8' 8.5'',10.6,9.50,11.50,NaN,NaN,NaN,None,NaN,NaN
59,2012,203100,Tony,Wroten,Tony Wroten,PG,76.75,6' 4.75'',78.00,6' 6'',...,8' 5'',5.2,8.00,9.00,30.0,35.5,10.75,None,3.24,0.0
60,2012,203092,Tyler,Zeller,Tyler Zeller,PF-C,83.25,6' 11.25'',84.50,7' 0.5'',...,8' 8.5'',6.4,9.00,9.75,30.0,34.0,11.13,None,3.40,16.0

In [4]:
display(getPlayerGames1('203076', '2016'))
display(getPlayerGames2('203076', '2016'))

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22016,203076,0021601184,"APR 07, 2017",NOP @ DEN,L,24,11,27,0.407,...,4,6,0,1,0,1,2,25,-2,1
1,22016,203076,0021601158,"APR 04, 2017",NOP vs. DEN,L,41,18,31,0.581,...,3,5,0,1,4,0,3,41,9,1
2,22016,203076,0021601146,"APR 02, 2017",NOP vs. CHI,L,40,8,19,0.421,...,9,11,2,3,1,3,2,30,-6,1
3,22016,203076,0021601132,"MAR 31, 2017",NOP vs. SAC,W,34,9,19,0.474,...,8,12,2,1,6,1,2,19,25,1
4,22016,203076,0021601117,"MAR 29, 2017",NOP vs. DAL,W,36,11,22,0.500,...,10,14,2,2,1,1,1,30,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,22016,203076,0021600060,"NOV 02, 2016",NOP @ MEM,L,36,3,13,0.231,...,6,7,1,2,3,5,5,10,-23,1
71,22016,203076,0021600051,"NOV 01, 2016",NOP vs. MIL,L,37,9,21,0.429,...,12,15,2,3,3,1,2,35,3,1
72,22016,203076,0021600032,"OCT 29, 2016",NOP @ SAS,L,32,6,15,0.400,...,5,5,0,0,3,1,1,18,-17,1
73,22016,203076,0021600025,"OCT 28, 2016",NOP vs. GSW,L,40,17,31,0.548,...,11,17,3,2,2,1,2,45,-3,1
74,22016,203076,0021600010,"OCT 26, 2016",NOP vs. DEN,L,41,17,34,0.500,...,14,15,5,5,4,3,4,50,-3,1

Empty DataFrame
Columns: [GAME_ID, GAME_DATE, HOME_TEAM_ID, VISITOR_TEAM_ID, HOME_TEAM_NAME, VISITOR_TEAM_NAME, HOME_TEAM_ABBREVIATION, VISITOR_TEAM_ABBREVIATION, HOME_TEAM_NICKNAME, VISITOR_TEAM_NICKNAME, GAME_TIME, HOME_WL, VISITOR_WL]
Index: []

In [111]:
getTeamBoxscore('0021401223')

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,FGM,FGA,FG_PCT,FG3M,...,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS
0,0021401223,1610612759,Spurs,SAS,San Antonio,240:00,45,79,0.570,3,...,4,32,36,33,2,3,15,20,103,-5.0
1,0021401223,1610612740,Pelicans,NOP,New Orleans,240:00,43,83,0.518,5,...,7,28,35,23,11,7,9,18,108,5.0